{% set version = "20191103" %}


package:
  name: pdfminer
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pdfminer/pdfminer-{{ version }}.tar.gz
  sha256: e8227cc99a48e06a931334a52cecfe9c45119ee652c8ea736445978a1c86b146

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python <3
    - pip
  run:
    - python <3

test:
  imports:
    - pdfminer

about:
  home: http://euske.github.io/pdfminer/index.html
  license: MIT
  license_file: LICENSE
  summary: 'PDF parser and analyzer'

extra:
  recipe-maintainers:
    - pmlandwehr
